repos:

#.py scripts starts#
#Reorder library imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--float-to-top"]
        name: isort (python)

#Black formatter
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

#Autoflake corrector
-   repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, -i]

##Tests##
#Check docstrings. Default Google style
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    -   id: darglint

#Code style Tests
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--max-line-length=100]
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
    -   id: pylint
        args: [--max-line-length=100]
#.py scripts ends#

#Jupyter notebooks starts#
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
    -   id: nbqa-isort
        args: [ --float-to-top ]
    #Formatters
    -   id: nbqa-black
    #-   id: nbqa-pyupgrade  #should be used carefully
    #    args: [--py37-plus]

        ##Tests##
        #Code style Tests
    -   id: nbqa-flake8
        args: [--max-line-length=100]
    -   id: nbqa-pylint
        args: [--max-line-length=100]
#Jupyter notebooks ends#
